version: "3.0"
services:
  employee-spring-boot:
    image: employee-spring-boot
    ports:
      - "9999:9999"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  
networks:
  employee-mysql: