// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GooglePageTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void googlePageTest() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("what is angular ");
    driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("rcnt")).click();
    js.executeScript("window.scrollTo(0,40)");
    js.executeScript("window.scrollTo(0,400)");
    {
      WebElement element = driver.findElement(By.cssSelector(".MjjYud:nth-child(3) .LC20lb > font > font"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MjjYud:nth-child(3) .LC20lb > font > font")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,280.79998779296875)");
    js.executeScript("window.scrollTo(0,1356.800048828125)");
    js.executeScript("window.scrollTo(0,2433.60009765625)");
    {
      WebElement element = driver.findElement(By.cssSelector("#videoTutorialPlaylist .content:nth-child(3) > h4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,2434.39990234375)");
    driver.findElement(By.cssSelector("#videoTutorialPlaylist .content:nth-child(3) > h4")).click();
    driver.findElement(By.cssSelector(".article-info > p")).click();
    js.executeScript("window.scrollTo(0,120)");
    driver.findElement(By.linkText("What Are Angular Components?")).click();
    js.executeScript("window.scrollTo(0,1700)");
    js.executeScript("window.scrollTo(0,2434.39990234375)");
    {
      WebElement element = driver.findElement(By.cssSelector(".PZPZlf:nth-child(2) font > font"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
